### ISSUE TITLE
Remove AvPlayer from Notification Center

### ISSUE THREAD

**Issue by sathishvgs** [jorgenhenrichsen/SwiftAudio#83]
Once the audio player has finished playing how can we remove the Player displaying in NotificationCenter or Lock Screen.

**Comment by jorgenhenrichsen** [comment]
Try calling the `NowPlayingInfoControllers` `clear()` function when you want to clear all info. This can be done by calling `player.nowPlayingInfoController.clear()`.

**Comment by sathishvgs** [comment]
Thanks, @jorgenhenrichsen . Now, it's working fine.

**Comment by curiousdustin** [comment]
@jorgenhenrichsen, is it expected that this will remove the controls from the lock screen, even if you are viewing the lock screen at the time?

I tested this in the example app by adding the following:

```swift
ViewController.swift
...
controller.player.event.playbackEnd.addListener(self, handlePlaybackEnd)
...
func handlePlaybackEnd(data: AudioPlayer.PlaybackEndEventData) {
    if data == .playedUntilEnd && controller.player.nextItems.count == 0 {
        controller.player.nowPlayingInfoController.clear()    
    }
}
```

When the last track ends while I am viewing the lock screen controls, instead of disappearing, the controls change to sort of a cleared default state. If I toggle the screen off and on again, the controls have disappeared as expected. If the last track ends while the screen is off, then I turn the screen on, the controls are also gone as expected.

![lock-screen-controls](https://user-images.githubusercontent.com/1706540/72178281-daafea80-339f-11ea-8920-997755be17e0.jpeg)

**Comment by curiousdustin** [comment]
I also tried this with the same results:
```swift
    func handlePlaybackEnd(data: AudioPlayer.PlaybackEndEventData) {
        if data == .playedUntilEnd && controller.player.nextItems.count == 0 {
            controller.player.stop()
            try? AudioSessionController.shared.deactivateSession()
            controller.player.nowPlayingInfoController.clear()
        }
    }
```

**Comment by curiousdustin** [comment]
The top answer here makes it seem like it should work:
https://stackoverflow.com/questions/52243428/how-to-vanish-player-controls-from-lockscreen-after-the-playback-has-finished-in

**Comment by curiousdustin** [comment]
@sathishvgs , can you confirm the controls disappear for you even if you are viewing them at the time?

**Comment by sathishvgs** [comment]
@curiousdustin , while listening audio we need the controls on Notification Center. If we dismiss the audio controller, it will be removed from the Notification Center. So, it's working for me.

**Comment by sathishvgs** [comment]
@curiousdustin ,
Shall I know what you are want to achieve? So, that I can help you.

**Comment by curiousdustin** [comment]
I’m talking about when the last track ends and there is nothing left to listen to. 

If I watch the lock screen / Notification Center controls, when the track is ending, they should disappear. But, they do not.

**Comment by debshyantan** [comment]
hi @sathishvgs ,

        controller.player.stop()
        controller.player.nowPlayingInfoController.clear()
        try? controller.audioSessionController.deactivateSession()
        controller.player.automaticallyUpdateNowPlayingInfo = true


i used the above code, the player stopper but mediaplayer in notificationcenter did not removed
